### ISSUE TITLE
Service cannot be accessed with its DNS name from a container

### ISSUE THREAD

**Issue by chunliu** [Azure/service-fabric-issues#1037]
I tried to deploy 2 Windows containers to a sf cluster with docker compose. The docker-compose.yml looks like this.  

```
version: '3'

services:
  todoweb:
    image: todoweb
    build:
      context: .\TodoWeb
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      TodoContext: "Data Source=db.todowebsfcontainer;Database=TodoWebDB;User Id=sa;Password=xxxxxxx;"
  db:
    image: microsoft/mssql-server-windows-developer
    environment:
      sa_password: "xxxxxxx"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
```

The DnsService is enabled in the cluster, and I configured the DNS name of the db service in the connection string, as shown the above. However, when I tried to curl the web, it returned an exception 

> The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. 

If I remote desktop to a node and try to connect the db with its name "db.todowebsfcontainer" from this node, it can be connected without problem. So it seems the DNS name works on the cluster node, but not from within another container. 

The container network is the default nat. Did I miss anything in this case?
