### ISSUE TITLE
[Question] How to open specific ports on SF nodes

### ISSUE THREAD

**Issue by ifle** [Azure/service-fabric-issues#814]
How to open specific ports on SF nodes. I have several services as containers that used socket communications and have a lot of socket communication exceptions. I connected to SF nodes with Remote Desktop for check which ports was been opened, but I not found my ports as opened.
For deploying I've used Service Fabric Deploy.
My services built on top of Orleans framework, that use to sockets for communication between services.
My compose file looks like 
```
version: '3'

services:
  mytestapp.web:
      image: ifle/mytestapp:web
      ports:
        - 8080:80
        - 30000:30000

  mytestapp.server:
    image: ifle/mytestapp:server
    ports:
      - 30000:30000
      - 11111:11111

networks:
  default:
    external:
      name: nat
```
